merge bootstrap-base changes to trunk
r47593

diff --git a/debian/bootstrap-base.postinst b/debian/bootstrap-base.postinst
--- a/debian/bootstrap-base.postinst
+++ b/debian/bootstrap-base.postinst
@@ -4,6 +4,8 @@ set -e
 . /usr/share/debconf/confmodule
 db_capb backup
 
+. /usr/lib/base-installer/library.sh
+
 ETCDIR=/target/etc
 ARCH=`udpkg --print-architecture`
 PROTOCOL=
@@ -28,36 +30,8 @@ KEYRING=/usr/share/keyrings/archive.gpg
 DEBCONF_ADMIN_EMAIL=""
 export DEBCONF_ADMIN_EMAIL
 
-# Avoid warnings from lvm2 tools about open file descriptors
-export LVM_SUPPRESS_FD_WARNINGS=1
-
-# Variables used to set the progress bar
-export PB_POSITION=0
-export PB_WAYPOINT_LENGTH=0
-
 SUBARCH="$(archdetect)"
 SUBARCH="${SUBARCH#*/}"
-
-log() {
-	logger -t base-installer "$@"
-}
-error() {
-	log "error: $*"
-}
-warning() {
-	log "warning: $*"
-}
-info() {
-	log "info: $*"
-}
-
-exit_error() {
-	error "exiting on error $1"
-	db_progress stop
-	db_input critical $1 || [ $? -eq 30 ]
-	db_go
-	exit 1
-}
 
 # See kernel/README for the architecture-specific functions expected here.
 if [ -f /usr/lib/base-installer/kernel.sh ]; then
@@ -77,36 +51,6 @@ else
 fi
 
 FLAVOUR="$(arch_get_kernel_flavour || true)"
-
-update_progress () {
-	# Updates the progress bar to a new position within the space allocated
-	# for the current waypoint. 
-	NW_POS=$(($PB_POSITION + $PB_WAYPOINT_LENGTH * $1 / $2))
-	db_progress SET $NW_POS
-}
-
-check_target () {
-	# Make sure something is mounted on the target.
-	# Partconf causes the latter format.
-	if ! grep -q '/target ' /proc/mounts && \
-			! grep -q '/target/ ' /proc/mounts; then
-		exit_error base-installer/no_target_mounted
-	fi
-	
-	# Warn about installation over an existing unix.
-	if [ -e /target/bin/sh -o -L /target/bin/sh ]; then
-		db_capb ""
-		db_input high base-installer/use_unclean_target || true
-		db_go || exit 10
-		db_capb backup
-		db_get base-installer/use_unclean_target
-		if [ "$RET" = false ]; then
-			db_reset base-installer/use_unclean_target
-			exit_error base-installer/unclean_target_cancel
-		fi
-		db_reset base-installer/use_unclean_target
-	fi
-}
 
 get_mirror_info () {
 	if [ -f /cdrom/.disk/base_installable ]; then
@@ -200,29 +144,6 @@ install_base_system () {
 		fi
 	fi
 	
-	# run the scripts found in hook directory before debootstrap
-	partsdir="/usr/lib/base-installer.d"
-	if [ -d "$partsdir" ]; then
-		for script in `ls "$partsdir"/*`; do
-			base=$(basename $script | sed 's/[0-9]*//')
-			if ! db_progress INFO base-installer/progress/$base; then
-				db_subst base-installer/progress/fallback SCRIPT "$base"
-				db_progress INFO base-installer/progress/fallback
-		    	fi
-	
-		    	if [ -x "$script" ] ; then
-				# be careful to preserve exit code
-				if log-output -t base-installer "$script"; then
-					:
-				else
-			    		warning "$script returned error code $?"
-				fi
-		    	else
-				error "Unable to execute $script"
-		    	fi
-		done
-	fi
-
 	# clean up after any past debootstrap run
 	rm -f /target/var/lib/apt/* 2>/dev/null || true
 	
@@ -249,133 +170,6 @@ install_base_system () {
 	fi
 
 	# Progress bar is now stepped to 100.
-}
-
-configure_apt () {
-	[ ! -d /target/etc/apt/apt.conf.d ] && mkdir -p /target/etc/apt/apt.conf.d
-	
-	# Make apt trust Debian CDs. This is not on by default (we think).
-	# This will be left in place on the installed system.
-	cat > /target/etc/apt/apt.conf.d/00trustcdrom <<EOT
-APT::Authentication::TrustCDROM "true";
-EOT
-
-	# Avoid clock skew causing gpg verification issues.
-	# This file will be left in place until the end of the install.
-	cat > /target/etc/apt/apt.conf.d/00IgnoreTimeConflict << EOT
-Acquire::gpgv::Options { "--ignore-time-conflict"; };
-EOT
-
-	if db_get debian-installer/allow_unauthenticated && [ "$RET" = true ]; then
-		# This file will be left in place until the end of the install.
-		cat > /target/etc/apt/apt.conf.d/00AllowUnauthenticated << EOT
-APT::Get::AllowUnauthenticated "true";
-Aptitude::CmdLine::Ignore-Trust-Violations "true";
-EOT
-	fi
-
-	# let apt inside the chroot see the cdrom
-	if [ "$PROTOCOL" = file ] ; then
-		if [ -n "$DIRECTORY" ]; then
-			umount /target$DIRECTORY 2>/dev/null || true
-			if [ ! -e /target/$DIRECTORY ]; then
-				mkdir -p /target/$DIRECTORY
-			fi
-		fi
-		if ! mount -o bind $DIRECTORY /target$DIRECTORY; then
-			warning "failed to bind mount /target$DIRECTORY"
-		fi
-		# The bind mount is left mounted after this postinst exits,
-		# for future apt-install calls to use.
-	fi
-
-	# sources.list uses space to separate the components, not comma
-	COMPONENTS=`echo $COMPONENTS | tr , " "`
-	APTSOURCE="$PROTOCOL://$MIRROR$DIRECTORY"
-
-	# This assumes the file protocol is only used for CD (image) installs
-	if [ "$PROTOCOL" = file ] ; then
-		# Make apt-cdrom and apt not unmount/mount CD-ROMs;
-		# needed to support CD images (hd-media installs)
-		# This file will be left in place until the end of the install.
-		cat > /target/etc/apt/apt.conf.d/00NoMountCDROM << EOT
-APT::CDROM::NoMount "true";
-Acquire::cdrom {
-  mount "/cdrom";
-  "/cdrom/" {
-    Mount  "true";
-    UMount "true";
-  };
-}
-EOT
-		# Scan CD-ROM or CD image; start with clean sources.list
-		: > /target/etc/apt/sources.list
-		if ! log-output -t base-installer chroot /target apt-cdrom add ; then
-			error "error while running apt-cdrom"
-		fi
-	else
-		echo "deb $APTSOURCE $DISTRIBUTION $COMPONENTS" > /target/etc/apt/sources.list
-	fi
-}
-
-create_devices () {
-	# RAID
-	if [ -e /proc/mdstat ] && grep -q ^md /proc/mdstat ; then
-		apt-install mdadm
-	fi
-	# device-mapper
-	if grep -q " device-mapper$" /proc/misc; then
-		mkdir -p /target/dev/mapper
-		if [ ! -e /target/dev/mapper/control ] ; then
-			major=$(grep "[0-9] misc$" /proc/devices | sed 's/[ ]\+misc//')
-			minor=$(grep "[0-9] device-mapper$" /proc/misc | sed 's/[ ]\+device-mapper//')
-			mknod /target/dev/mapper/control c $major $minor
-
-			# check if root is on a dm-crypt device
-			rootdev=$(mount | grep "on /target " | cut -d' ' -f1)
-			rootnode=${rootdev#/dev/mapper/}
-			if [ $rootdev != $rootnode ] && type dmsetup >/dev/null 2>&1 && \
-			   [ "$(dmsetup table $rootnode | cut -d' ' -f3)" = crypt ]; then
-				major="$(dmsetup -c --noheadings info $rootnode | cut -d':' -f2)"
-				minor="$(dmsetup -c --noheadings info $rootnode | cut -d':' -f3)"
-				mknod /target/dev/mapper/$rootnode b $major $minor
-			fi
-
-			# Create device nodes for fake (ata) RAID devices
-			if type dmraid >/dev/null 2>&1; then
-				for frdisk in $(dmraid -s -c | grep -v "No RAID disks"); do
-					for frdev in $(ls /dev/mapper/$frdisk* 2>/dev/null); do
-						frnode=$(basename $frdev)
-						major="$(dmsetup -c --noheadings info $frnode | cut -d':' -f2)"
-						minor="$(dmsetup -c --noheadings info $frnode | cut -d':' -f3)"
-						mknod /target/dev/mapper/$frnode b $major $minor
-					done
-				done
-			fi
-		fi
-
-		# We can't check the root node directly as is done above because
-		# root could be on an LVM LV on top of an encrypted device
-		if type dmsetup >/dev/null 2>&1 && \
-		   dmsetup table | cut -d' ' -f4 | grep -q "crypt" 2>/dev/null; then
-			apt-install cryptsetup
-		fi
-
-		if type dmraid >/dev/null 2>&1; then
-			if [ "$(dmraid -s -c | grep -v "No RAID disks")" ]; then
-				apt-install dmraid
-			fi
-		fi
-
-		if pvdisplay | grep -iq "physical volume ---"; then
-			apt-install lvm2
-			in-target vgscan --mknodes || true
-		fi
-	fi
-	# UML: create ubd devices
-	if grep -q "model.*UML" /proc/cpuinfo; then
-		chroot /target /bin/sh -c '(cd /dev; ./MAKEDEV ubd)'
-	fi
 }
 
 kernel_update_list () {
@@ -501,82 +295,6 @@ pick_kernel () {
 
 	# Pass the kernel name on
 	db_set base-installer/kernel/image "$KERNEL"
-}
-
-get_resume_partition () {
-	biggest_size=0
-	biggest_partition=
-	while read filename type size other; do
-		if [ "$type" != partition ]; then
-			continue
-		fi
-		if [ "$size" -gt "$biggest_size" ]; then
-			biggest_size="$size"
-			biggest_partition="$filename"
-		fi
-	done < /proc/swaps
-	echo "$biggest_partition"
-}
-
-available_initramfs_generators () {
-	irf_list=""
-	db_get base-installer/kernel/linux/initramfs-generators || return 1
-
-	for irf in $RET; do
-		if LANG=C chroot /target apt-cache policy $irf 2>&1 | \
-			grep "Candidate:" | grep -v "(none)" >/dev/null 2>&1; then
-			if [ "$irf_list" ]; then
-				irf_list="$irf_list $irf"
-			else
-				irf_list="$irf"
-			fi
-		fi
-	done
-	info "Available initramfs generator(s): '$irf_list'"
-
-	[ "$irf_list" ] || return 1
-	echo "$irf_list"
-	return 0
-}
-
-select_initramfs_generator () {
-	irf_choices="$(echo "$1" | sed "s/ \+/, /g")"
-	irf_default="${1%% *}"
-	db_subst base-installer/initramfs/generator GENERATORS "$irf_choices"
-	db_set base-installer/initramfs/generator "$irf_default"
-
-	db_input low base-installer/initramfs/generator || [ $? -eq 30 ]
-	if ! db_go; then
-		db_progress stop
-		exit 10
-	fi
-
-	db_get base-installer/initramfs/generator
-	echo $RET
-}
-
-addmodule_easy () {
-	if [ -f "$CFILE" ]; then
-		if [ "$2" = 1 ]; then
-			echo -e "\n# Added by Debian Installer" >>$CFILE
-		fi
-		echo "$1" >> $CFILE
-	fi
-}
-
-addmodule_initramfs_tools () {
-	CFILE='/target/etc/initramfs-tools/modules'
-	addmodule_easy "$1" "$2"
-}
-
-addmodule_yaird () {
-	CFILE='/target/etc/yaird/Default.cfg'
-	if [ -f "$CFILE" ]; then
-		if [ "$2" = 1 ]; then
-			sed -i "/END GOALS/s/^/\n\t\t#\n\t\t# Added by Debian Installer\n/" $CFILE
-		fi
-		sed -i "/END GOALS/s/^/\t\tMODULE $1\n/" $CFILE
-	fi
 }
 
 install_linux () {
@@ -764,77 +482,124 @@ EOF
 	fi
 }
 
-install_pcmcia_modules () {
-	if [ "$KERNEL" = none ]; then
-		info "Not installing any pcmcia modules"
-		return
-	fi
-	# Note pcmcia modules are only separate for 2.4 kernels, which
-	# use the old kernel-image names.
-	pcmcia_package=$(echo "$KERNEL" | sed 's/^kernel-image/kernel-pcmcia-modules/')
-	info "Installing pcmcia modules package '$pcmcia_package'."
-	log-output -t base-installer apt-install "$pcmcia_package" || true
+get_resume_partition () {
+	biggest_size=0
+	biggest_partition=
+	while read filename type size other; do
+		if [ "$type" != partition ]; then
+			continue
+		fi
+		if [ "$size" -gt "$biggest_size" ]; then
+			biggest_size="$size"
+			biggest_partition="$filename"
+		fi
+	done < /proc/swaps
+	echo "$biggest_partition"
 }
 
-apt_update () {
-	log-output -t base-installer chroot /target apt-get update \
-		|| apt_update_failed=$?
-	
-	if [ "$apt_update_failed" ]; then
-		warning "apt update failed: $apt_update_failed"
-	fi
-}
+available_initramfs_generators () {
+	irf_list=""
+	db_get base-installer/kernel/linux/initramfs-generators || return 1
 
-install_extra () {
-	info "Installing queued packages into /target/."
-	
-	if [ -f /var/lib/apt-install/queue ] ; then
-		# We need to install these one by one in case one fails.
-		PKG_COUNT=`cat /var/lib/apt-install/queue | wc -w`
-		CURR_PKG=0
-		for PKG in `cat /var/lib/apt-install/queue`; do
-			db_subst base-installer/section/install_extra_package SUBST0 "$PKG"
-			db_progress INFO base-installer/section/install_extra_package
-
-			if ! log-output -t base-installer apt-install $PKG; then
-				warning "Failed to install $PKG into /target/: $?"
-			fi
-
-			# Advance progress bar within space allocated for install_extra
-			CURR_PKG=$(($CURR_PKG + 1))
-			update_progress $CURR_PKG $PKG_COUNT
-		done
-	fi
-}
-
-post_install_hooks () {
-	partsdir="/usr/lib/post-base-installer.d"
-	if [ -d "$partsdir" ]; then
-		scriptcount=`ls "$partsdir"/* | wc -l`
-		scriptcur=0
-		for script in "$partsdir"/*; do
-			base="$(basename "$script" | sed 's/[0-9]*//')"
-			if ! db_progress INFO base-installer/progress/$base && \
-			   ! db_progress INFO finish-install/progress/$base && \
-			   ! db_progress INFO prebaseconfig/progress/$base; then
-				db_subst base-installer/progress/fallback SCRIPT "$base"
-				db_progress INFO base-installer/progress/fallback
-			fi
-
-			if [ -x "$script" ]; then
-				# be careful to preserve exit code
-				if log-output -t base-installer "$script"; then
-					:
-				else
-					warning "$script returned error code $?"
-				fi
+	for irf in $RET; do
+		if LANG=C chroot /target apt-cache policy $irf 2>&1 | \
+			grep "Candidate:" | grep -v "(none)" >/dev/null 2>&1; then
+			if [ "$irf_list" ]; then
+				irf_list="$irf_list $irf"
 			else
-				error "Unable to execute $script"
+				irf_list="$irf"
 			fi
+		fi
+	done
+	info "Available initramfs generator(s): '$irf_list'"
 
-			scriptcur="$(($scriptcur + 1))"
-			update_progress "$scriptcur" "$scriptcount"
-		done
+	[ "$irf_list" ] || return 1
+	echo "$irf_list"
+	return 0
+}
+
+select_initramfs_generator () {
+	irf_choices="$(echo "$1" | sed "s/ \+/, /g")"
+	irf_default="${1%% *}"
+	db_subst base-installer/initramfs/generator GENERATORS "$irf_choices"
+	db_set base-installer/initramfs/generator "$irf_default"
+
+	db_input low base-installer/initramfs/generator || [ $? -eq 30 ]
+	if ! db_go; then
+		db_progress stop
+		exit 10
+	fi
+
+	db_get base-installer/initramfs/generator
+	echo $RET
+}
+
+addmodule_easy () {
+	if [ -f "$CFILE" ]; then
+		if [ "$2" = 1 ]; then
+			echo -e "\n# Added by Debian Installer" >>$CFILE
+		fi
+		echo "$1" >> $CFILE
+	fi
+}
+
+addmodule_initramfs_tools () {
+	CFILE='/target/etc/initramfs-tools/modules'
+	addmodule_easy "$1" "$2"
+}
+
+addmodule_yaird () {
+	CFILE='/target/etc/yaird/Default.cfg'
+	if [ -f "$CFILE" ]; then
+		if [ "$2" = 1 ]; then
+			sed -i "/END GOALS/s/^/\n\t\t#\n\t\t# Added by Debian Installer\n/" $CFILE
+		fi
+		sed -i "/END GOALS/s/^/\t\tMODULE $1\n/" $CFILE
+	fi
+}
+
+configure_apt () {
+	# let apt inside the chroot see the cdrom
+	if [ "$PROTOCOL" = file ] ; then
+		if [ -n "$DIRECTORY" ]; then
+			umount /target$DIRECTORY 2>/dev/null || true
+			if [ ! -e /target/$DIRECTORY ]; then
+				mkdir -p /target/$DIRECTORY
+			fi
+		fi
+		if ! mount -o bind $DIRECTORY /target$DIRECTORY; then
+			warning "failed to bind mount /target$DIRECTORY"
+		fi
+		# The bind mount is left mounted, for future apt-install
+		# calls to use.
+	fi
+
+	# sources.list uses space to separate the components, not comma
+	COMPONENTS=`echo $COMPONENTS | tr , " "`
+	APTSOURCE="$PROTOCOL://$MIRROR$DIRECTORY"
+
+	# This assumes the file protocol is only used for CD (image) installs
+	if [ "$PROTOCOL" = file ] ; then
+		# Make apt-cdrom and apt not unmount/mount CD-ROMs;
+		# needed to support CD images (hd-media installs)
+		# This file will be left in place until the end of the install.
+		cat > /target/etc/apt/apt.conf.d/00NoMountCDROM << EOT
+APT::CDROM::NoMount "true";
+Acquire::cdrom {
+  mount "/cdrom";
+  "/cdrom/" {
+    Mount  "true";
+    UMount "true";
+  };
+}
+EOT
+		# Scan CD-ROM or CD image; start with clean sources.list
+		: > /target/etc/apt/sources.list
+		if ! log-output -t base-installer chroot /target apt-cdrom add ; then
+			error "error while running apt-cdrom"
+		fi
+	else
+		echo "deb $APTSOURCE $DISTRIBUTION $COMPONENTS" > /target/etc/apt/sources.list
 	fi
 }
 
@@ -842,41 +607,19 @@ cleanup () {
 	rm -f $KERNEL_LIST
 }
 
-WAYPOINTS=""
-NUM_STEPS=0
-waypoint () {
-	WAYPOINTS="$WAYPOINTS $1:$2"
-	NUM_STEPS=$(($NUM_STEPS + $1)) || true
-}
-
 waypoint 1	check_target
 waypoint 1	get_mirror_info
+waypoint 1	pre_install_hooks
 waypoint 100	install_base_system
+waypoint 1	configure_apt_preferences
 waypoint 1	configure_apt
 waypoint 3	apt_update
 waypoint 2	create_devices
 waypoint 5	post_install_hooks
 waypoint 1	pick_kernel
 waypoint 20	install_linux
-case "$ARCH" in
-	i386*)
-		if [ -e /proc/bus/pccard/drivers ]; then
-			waypoint 1	install_pcmcia_modules
-		fi
-	;;
-esac
 waypoint 10	install_extra
 waypoint 0	cleanup
 
-db_progress START 0 $NUM_STEPS base-installer/progress/installing-debian
-for item in $WAYPOINTS; do
-	PB_WAYPOINT_LENGTH=$(echo $item | cut -d: -f 1)
-	WAYPOINT=$(echo $item | cut -d: -f 2)
-	# Not all of the section headers need exist.
-	db_progress INFO "base-installer/section/$WAYPOINT" || true
-	eval $WAYPOINT
-	PB_POSITION=$(($PB_POSITION + $PB_WAYPOINT_LENGTH)) || true
-	db_progress SET $PB_POSITION
-done
-db_progress STOP
+run_waypoints
 exit 0
