* Joey Hess     - Use the user-params command to get parameters the user manually       entered on the command line, and add these into the grub config file.
r19428

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -178,6 +178,22 @@ update_mtab() {
 	done ) > $mtab
 }
 
+# Run update-grub in /target.
+update_grub () {
+	# Pipe from 'yes' to tell grub to create menu.lst when it is missing. A
+	# better correct fix is to get update-grub to be able to run in
+	# noninteractive mode.  Newer versions of the grub package support
+	# '-y' for noninteractive installs.  But we'll keep it as-is for
+	# Skolelinux.
+	if ! chroot /target /usr/bin/yes | chroot /target /sbin/update-grub >> $log 2>&1 ; then
+		error "Running 'update-grub' failed." 1>&2
+		db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
+		db_go || true
+		db_progress STOP
+		exit 1
+	fi
+}
+
 is_floppy () {
 	# FIXME: this is lame, and does not yet support /dev devices.
 	echo "$1" | grep -q '(fd'
@@ -347,18 +363,15 @@ db_progress INFO grub-installer/progress/step_config_loader
 
 # Delete for idempotency.
 rm -f /target/boot/grub/menu.lst
+update_grub
 
-# Pipe from 'yes' to tell grub to create menu.lst when it is missing A
-# better correct fix is to get update-grub to be able to run in
-# noninteractive mode.  Newer versions of the grub package support
-# '-y' for noninteractive installs.  But we'll keep it as-is for
-# Skolelinux.
-if ! chroot /target /usr/bin/yes | chroot /target /sbin/update-grub >> $log 2>&1 ; then
-	error "Running 'update-grub' failed." 1>&2
-	db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
-	db_go || true
-	db_progress STOP
-	exit 1
+user_params=$(echo $(user-params)) || true
+if [ -n "$user_params" ]; then
+	# Modify menu.lst to include user parameters.
+	sed "s!^\(# kopt=.*\)!\1 $user_params!" \
+		< /target/boot/grub/menu.lst > /target/boot/grub/menu.lst.new
+	mv /target/boot/grub/menu.lst.new /target/boot/grub/menu.lst
+	update_grub # again, to add new options to all the Debian kernel entries
 fi
 
 # Generation menu.lst addition for other OSes.
