consitent indentaton (exscept in the convert function which is copied out of install-grub)
r13181

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -12,15 +12,15 @@ db_capb backup
 log=/var/log/messages
 
 log() {
-    logger -t grub-installer "$@"
+	logger -t grub-installer "$@"
 }
 
 error() {
-    log "error: $@"
+	log "error: $@"
 }
 
 info() {
-    log "info: $@"
+	log "info: $@"
 }
 
 # This is copied from update-grub. We've requested that it be moved
@@ -153,16 +153,16 @@ hurd_convert () {
 
 # Make sure mtab in the chroot reflects the currently mounted partitions.
 update_mtab() {
-    mtab=/target/etc/mtab
-    grep /target /proc/mounts | (
+	mtab=/target/etc/mtab
+	grep /target /proc/mounts | (
 	while read devpath mountpoint fstype options n1 n2 ; do
-	    devpath=`mapdevfs $devpath || echo $devpath`
-	    mountpoint=`echo $mountpoint | sed s%^/target%%`
-	    # The sed line remove the mount point for root.
-	    if [ -z "$mountpoint" ] ; then
-		mountpoint="/"
-	    fi
-	    echo $devpath $mountpoint $fstype $options $n1 $n2
+		devpath=`mapdevfs $devpath || echo $devpath`
+		mountpoint=`echo $mountpoint | sed s%^/target%%`
+		# The sed line removes the mount point for root.
+		if [ -z "$mountpoint" ] ; then
+			mountpoint="/"
+		fi
+		echo $devpath $mountpoint $fstype $options $n1 $n2
 	done ) > $mtab
 }
 
@@ -292,14 +292,14 @@ fi
 
 info "Running chroot /target /sbin/grub-install $floppyparam \"$bootdev\""
 if chroot /target /sbin/grub-install $floppyparam "$bootdev" >> $log 2>&1 ; then
-    info "grub-install ran successfully"
+	info "grub-install ran successfully"
 else
-    error "Running 'grub-install $floppyparam \"$bootdev\"' failed."
-    db_subst grub-installer/grub-install-failed BOOTDEV "$bootdev"
-    db_input critical grub-installer/grub-install-failed || [ $? -eq 30 ]
-    db_go || true
-    db_progress STOP
-    exit 1
+	error "Running 'grub-install $floppyparam \"$bootdev\"' failed."
+	db_subst grub-installer/grub-install-failed BOOTDEV "$bootdev"
+	db_input critical grub-installer/grub-install-failed || [ $? -eq 30 ]
+	db_go || true
+	db_progress STOP
+	exit 1
 fi
 
 db_progress STEP 1
@@ -314,11 +314,11 @@ rm -f /target/boot/grub/menu.lst
 # '-y' for noninteractive installs.  But we'll keep it as-is for
 # Skolelinux.
 if ! chroot /target /usr/bin/yes | chroot /target /sbin/update-grub >> $log 2>&1 ; then
-    error "Running 'update-grub' failed." 1>&2
-    db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
-    db_go || true
-    db_progress STOP
-    exit 1
+	error "Running 'update-grub' failed." 1>&2
+	db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
+	db_go || true
+	db_progress STOP
+	exit 1
 fi
 
 # Now add any other OSes to the end of menu.lst.
@@ -444,10 +444,10 @@ db_progress INFO grub-installer/progress/step_update_etc
 
 sed -e 's/do_bootloader = yes/do_bootloader = no/' < /target/etc/kernel-img.conf > /target/etc/kernel-img.conf.$$
 if [ -z "`grep update-grub /target/etc/kernel-img.conf.$$`" ]; then
-    (
-      echo "postinst_hook = /sbin/update-grub"
-      echo "postrm_hook   = /sbin/update-grub"
-    ) >> /target/etc/kernel-img.conf.$$
+	(
+		echo "postinst_hook = /sbin/update-grub"
+		echo "postrm_hook   = /sbin/update-grub"
+	) >> /target/etc/kernel-img.conf.$$
 fi
 mv /target/etc/kernel-img.conf.$$ /target/etc/kernel-img.conf
 
