Re-implement the use of log-output using the new version written in C
r31590

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,7 +4,6 @@ set -e
 . /usr/share/debconf/confmodule
 db_capb backup
 
-LOGFILE=/var/log/messages
 ETCDIR=/target/etc
 ARCH=`udpkg --print-architecture`
 PROTOCOL=
@@ -240,15 +239,15 @@ install_base_system () {
 	if search-path cdebootstrap; then
 		cdebootstrap || debootstrap_failed=$?
 	else
-		run-debootstrap \
-		        --components="${COMPONENTS}" \
-		        --debian-installer \
+		log-output -t debootstrap run-debootstrap \
+			--components="${COMPONENTS}" \
+			--debian-installer \
 			--resolve-deps \
-		        ${include} ${exclude} \
-		        ${keyring} \
-		        ${DISTRIBUTION} /target \
-		        "$PROTOCOL://$MIRROR$DIRECTORY" \
-			2>> /var/log/messages || debootstrap_failed=$?
+			${include} ${exclude} \
+			${keyring} \
+			${DISTRIBUTION} /target \
+			"$PROTOCOL://$MIRROR$DIRECTORY" \
+			|| debootstrap_failed=$?
 	fi
 
 	if [ true = "$copied_fstab" ] ; then
@@ -530,7 +529,7 @@ EOF
 		# configuration
 		db_subst base-installer/section/install_kernel_package SUBST0 "initrd-tools"
 		db_progress INFO base-installer/section/install_kernel_package
-		if ! apt-install initrd-tools 2>> $LOGFILE ; then
+		if ! log-output -t base-installer apt-install initrd-tools; then
 			db_subst base-installer/kernel/failed-package-install PACKAGE initrd-tools
 			exit_error base-installer/kernel/failed-package-install
 		fi
@@ -572,7 +571,7 @@ EOF
 	info "Installing kernel '$KERNEL'."
 	db_subst base-installer/section/install_kernel_package SUBST0 "$KERNEL"
 	db_progress INFO base-installer/section/install_kernel_package
-	apt-install "$KERNEL" 2>> $LOGFILE || kernel_install_failed=$?
+	log-output -t base-installer apt-install "$KERNEL" || kernel_install_failed=$?
 
 	# Advance progress bar to 90% of allocated space for install_kernel
 	update_progress 90 100
@@ -603,11 +602,13 @@ install_pcmcia_modules () {
 	# use the old kernel-image names.
 	pcmcia_package=$(echo "$KERNEL" | sed 's/^kernel-image/kernel-pcmcia-modules/')
 	info "Installing pcmcia modules package '$pcmcia_package'."
-	apt-install "$pcmcia_package" 2>> $LOGFILE || true
+	log-output -t base-installer apt-install "$pcmcia_package" || true
 }
 
 apt_update () {
-	chroot /target apt-get -o Acquire::gpgv::Options::=--ignore-time-conflict update >> $LOGFILE 2>&1 || apt_update_failed=$?
+	log-output -t base-installer chroot /target \
+		apt-get -o Acquire::gpgv::Options::=--ignore-time-conflict update \
+		|| apt_update_failed=$?
 	
 	if [ "$apt_update_failed" ]; then
 		warning "apt update failed: $apt_update_failed"
@@ -625,7 +626,7 @@ install_extra () {
 			db_subst base-installer/section/install_extra_package SUBST0 "$PKG"
 			db_progress INFO base-installer/section/install_extra_package
 
-			if apt-install $PKG >> $LOGFILE 2>&1 ; then
+			if log-output -t base-installer apt-install $PKG; then
 				info "Installed $PKG successfully into /target/"
 			else
 				warning "Failed to install $PKG into /target/: $?"
