Correct log message.
r8277

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -482,7 +482,7 @@ install_extra () {
 			if apt-install $PKG >> $LOGFILE 2>&1 ; then
 				log "Installed $PKG successfully into /target/"
 			else
-				log "Failed to $PKG successfully into /target/: $?"
+				log "Failed to install $PKG into /target/: $?"
 			fi
 		done
 	fi
