- Depend on os-prober, and add stanzas to menu.lst for chainloaded       operating systems. Closes: #237185, #238293, #240228       (No support for other linux systems yet though.)
r12499

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,6 +4,9 @@ set -e
 . /usr/share/debconf/confmodule
 #set -x
 
+newline="
+"
+
 db_capb backup
 
 log=/var/log/messages
@@ -18,6 +21,116 @@ error() {
 
 info() {
     log "info: $@"
+}
+
+# This is copied from update-grub. We've requested that it be moved
+# to a utility or shell library.
+device_map=/target/boot/grub/device.map
+# Usage: convert os_device
+# Convert an OS device to the corresponding GRUB drive.
+# This part is OS-specific.
+convert () {
+#    # First, check if the device file exists.
+#    if test -e "$1"; then
+#		:
+#    else
+#		echo "$1: Not found or not a block device." 1>&2
+#		exit 1
+#    fi
+
+	host_os=`uname -s | tr '[A-Z]' '[a-z]'`
+
+    # Break the device name into the disk part and the partition part.
+    case "$host_os" in
+    linux*)
+		tmp_disk=`echo "$1" | sed -e 's%\([sh]d[a-z]\)[0-9]*$%\1%' \
+				  -e 's%\(fd[0-9]*\)$%\1%' \
+				  -e 's%/part[0-9]*$%/disc%' \
+				  -e 's%\(c[0-7]d[0-9]*\).*$%\1%'`
+		tmp_part=`echo "$1" | sed -e 's%.*/[sh]d[a-z]\([0-9]*\)$%\1%' \
+				  -e 's%.*/fd[0-9]*$%%' \
+				  -e 's%.*/floppy/[0-9]*$%%' \
+				  -e 's%.*/\(disc\|part\([0-9]*\)\)$%\2%' \
+				  -e 's%.*c[0-7]d[0-9]*p*%%'`
+	;;
+    gnu*)
+		tmp_disk=`echo "$1" | sed 's%\([sh]d[0-9]*\).*%\1%'`
+		tmp_part=`echo "$1" | sed "s%$tmp_disk%%"` ;;
+    freebsd*)
+		tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([saw]d[0-9]*\).*$%r\1%' \
+			    | sed 's%r\{0,1\}\(da[0-9]*\).*$%r\1%'`
+		tmp_part=`echo "$1" \
+	    		| sed "s%.*/r\{0,1\}[saw]d[0-9]\(s[0-9]*[a-h]\)%\1%" \
+       	    	| sed "s%.*/r\{0,1\}da[0-9]\(s[0-9]*[a-h]\)%\1%"`
+	;;
+    netbsd*)
+		tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([sw]d[0-9]*\).*$%r\1d%' \
+	    		| sed 's%r\{0,1\}\(fd[0-9]*\).*$%r\1a%'`
+		tmp_part=`echo "$1" \
+	    		| sed "s%.*/r\{0,1\}[sw]d[0-9]\([abe-p]\)%\1%"`
+	;;
+    *)
+		echo "update-grub does not support your OS yet." 1>&2
+		exit 1 ;;
+    esac
+
+    # Get the drive name.
+    tmp_drive=`grep -v '^#' $device_map | grep "$tmp_disk *$" \
+			| sed 's%.*\(([hf]d[0-9][a-g0-9,]*)\).*%\1%'`
+
+    # If not found, print an error message and exit.
+    if test "x$tmp_drive" = x; then
+		echo "$1 does not have any corresponding BIOS drive." 1>&2
+		exit 1
+    fi
+
+    if test "x$tmp_part" != x; then
+		# If a partition is specified, we need to translate it into the
+		# GRUB's syntax.
+		case "$host_os" in
+		linux*)
+	    	echo "$tmp_drive" | sed "s%)$%,`expr $tmp_part - 1`)%" ;;
+		gnu*)
+	    	if echo $tmp_part | grep "^s" >/dev/null; then
+				tmp_pc_slice=`echo $tmp_part \
+		    		| sed "s%s\([0-9]*\)[a-g]*$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
+	    	fi
+	    	if echo $tmp_part | grep "[a-g]$" >/dev/null; then
+				tmp_bsd_partition=`echo "$tmp_part" \
+		    		| sed "s%[^a-g]*\([a-g]\)$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,$tmp_bsd_partition)%"`
+	    	fi
+	    	echo "$tmp_drive" ;;
+		freebsd*)
+	    	if echo $tmp_part | grep "^s" >/dev/null; then
+				tmp_pc_slice=`echo $tmp_part \
+		    		| sed "s%s\([0-9]*\)[a-h]*$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
+	    	fi
+	    	if echo $tmp_part | grep "[a-h]$" >/dev/null; then
+				tmp_bsd_partition=`echo "$tmp_part" \
+		    		| sed "s%s\{0,1\}[0-9]*\([a-h]\)$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,$tmp_bsd_partition)%"`
+	    	fi
+	    	echo "$tmp_drive" ;;
+		netbsd*)
+	    	if echo $tmp_part | grep "^[abe-p]$" >/dev/null; then
+				tmp_bsd_partition=`echo "$tmp_part" \
+		    		| sed "s%\([a-p]\)$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,$tmp_bsd_partition)%"`
+	    	fi
+	    	echo "$tmp_drive" ;;
+		esac
+    else
+		# If no partition is specified, just print the drive name.
+		echo "$tmp_drive"
+    fi
 }
 
 # Make sure mtab in the chroot reflect the currently mounted partitions.
@@ -40,8 +153,12 @@ is_floppy () {
 	echo "$1" | grep -q "\(fd"
 }
 
-db_progress START 0 5 grub-installer/progress/title
+db_progress START 0 6 grub-installer/progress/title
 
+db_progress INFO grub-installer/progress/step_os-probe
+os-prober > /tmp/os-probed || true
+
+db_progress STEP 1
 db_progress INFO grub-installer/progress/step_install
 
 if ! apt-install grub ; then
@@ -118,6 +235,37 @@ else
     db_progress STOP
     exit 1
 fi
+
+# Now add any other OSes to the end of menu.lst.
+OLDIFS="$IFS"
+IFS="$newline"
+for os in $(cat /tmp/os-probed); do
+	IFS="$OLDIFS"
+	title=$(echo "$os" | cut -d: -f2)
+	type=$(echo "$os" | cut -d: -f4)
+	partition=$(mapdevfs $(echo "$os" | cut -d: -f1))
+	grubdrive=$(convert "$partition") || true
+	if [ -n "$grubdrive" ]; then
+		case "$type" in
+			chain)
+				cat >> /target/boot/grub/menu.lst <<EOF
+
+title		$title
+root		$grubdrive
+makeactive
+chainloader	+1
+
+EOF
+			;;
+			*)
+				info "unhandled: $os"
+			;;
+		esac
+	fi
+	IFS="$newline"
+done
+IFS="$OLDIFS"
+rm -f /tmp/os-probed
 
 db_progress STEP 1
 db_progress INFO grub-installer/progress/step_update_etc
