* Delete any cruft left behind by a past debootstrap run in   /target/var/lib/apt. This avoids a problem where 1) debootstrap is run   before dinstall 2) Packages file download fails and aborts the run 3)   debootstrap is re-run after dinstall, does not refresh Release file, and   fails since the new Packages file it does download has a m5sum mismatch   with the old Release file. (Ah, the joys of running d-i on dialup..)
r31816

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -234,6 +234,9 @@ install_base_system () {
 		done
 	fi
 
+	# clean up after any past debootstrap run
+	rm -f /target/var/lib/apt/* 2>/dev/null || true
+	
 	if search-path cdebootstrap; then
 		cdebootstrap || debootstrap_failed=$?
 	else
