Support creating and mounting a ZFS (not ZVOL) and make it a root file system.

diff --git a/mount.d/zfs b/mount.d/zfs
--- a/mount.d/zfs
+++ b/mount.d/zfs
@@ -9,9 +9,28 @@ options=$4
 dump=$5
 pass=$6
 
+log_exec() {
+	log-output -t partman-zfs --pass-stdout $* || exit 1
+}
+
 case $type in
     zfs)
-	zfs set mountpoint=/${mp#/} ${fs#/dev/zvol/} || exit 1
+	if echo "$fs" | grep -Eq '^/'; then
+	    # ZVOL
+	    log_exec zfs set mountpoint=/${mp#/} ${fs#/dev/zvol/}
+	else
+	    # ZFS
+	    if [ "$mp" = "/var" ]; then
+		# NOTE: !!! DANGEROUS !!!
+		# /lib/partman/finish.d/20mount_partitions creates '/target/var/{lock,run}'
+		# and ZFS don't do overlay mounts by default. And it might not be a
+		# good idea to do one here - the mount might (will?) fail at next boot.
+		rm -Rvf /target/var
+	    fi
+
+	    log_exec zfs set mountpoint=$mp $fs
+	    log_exec zfs mount $fs
+	fi
 	exit 0
 	;;
 esac
